Add files via upload
Now logs can be found in the logs directory /storage/emulated/0/logs

diff --git a/elementalx b/elementalx
--- a/elementalx
+++ b/elementalx
@@ -104,3 +104,25 @@ fstrim /data;
 fstrim /cache; 
 fstrim /system;
 
+# Auto-generate log directory;
+mkdir -p /storage/emulated/0/logs
+
+# Script log file location;
+LOG_FILE=/storage/emulated/0/logs
+
+export TZ=$(getprop persist.sys.timezone);
+echo $(date) > /storage/emulated/0/logs/elementalx.log
+if [ $? -eq 0 ]
+then
+  echo "Successfully applied Enjoy The Tweaks!" >> /storage/emulated/0/logs/elementalx.log
+  exit 0
+else
+  echo "Failed...please share logs with me" >> /storage/emulated/0/logs/elementalx.log
+  exit 1
+fi
+  
+# Wait..
+# Done!
+#
+
+
diff --git a/ondemand b/ondemand
--- a/ondemand
+++ b/ondemand
@@ -102,3 +102,24 @@ setprop persist.radio.add_power_save 1
 fstrim /data;
 fstrim /cache; 
 fstrim /system;
+
+# Auto-generate;
+mkdir -p /storage/emulated/0/logs
+
+# Script log file location;
+LOG_FILE=/storage/emulated/0/logs
+
+export TZ=$(getprop persist.sys.timezone);
+echo $(date) > /storage/emulated/0/logs/ondemand.log
+if [ $? -eq 0 ]
+then
+  echo "Enjoy!" >> /storage/emulated/0/logs/ondemand.log
+  exit 0
+else
+  echo "reasons failed" >> /storage/emulated/0/logs/ondemand.log
+  exit 1
+fi
+  
+# Wait..
+# Done!
+#
diff --git a/sched b/sched
--- a/sched
+++ b/sched
@@ -91,3 +91,25 @@ fstrim /data;
 fstrim /cache; 
 fstrim /system;
 
+# Auto-generate log directory;
+mkdir -p /storage/emulated/0/logs
+
+# Script log file location;
+LOG_FILE=/storage/emulated/0/logs
+
+export TZ=$(getprop persist.sys.timezone);
+echo $(date) > /storage/emulated/0/logs/sched.log
+if [ $? -eq 0 ]
+then
+  echo "Successfully applied Enjoy The Tweaks!" >> /storage/emulated/0/logs/sched.log
+  exit 0
+else
+  echo "Failed...please share logs with me" >> /storage/emulated/0/logs/sched.log
+  exit 1
+fi
+  
+# Wait..
+# Done!
+#
+
+
